services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: node server.js